/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package it.map.graphicadventure.progettoesame.view;

import it.map.graphicadventure.progettoesame.model.Zombie;
import it.map.graphicadventure.progettoesame.model.GameObject;
import it.map.graphicadventure.progettoesame.model.Player;
import it.map.graphicadventure.progettoesame.model.items.Weapon;
import java.awt.Frame;
import java.util.List;
import javax.swing.SwingUtilities;

/**
 * Finestra di dialogo modale che gestisce l'interfaccia 
 * grafica e la logica di combattimento a turni.
 *
 * Nel pattern architetturale MVC, funge da View per mostrare le statistiche di scontro, 
 * ma incorpora anche la logica locale per la risoluzione dei turni. È progettata come 
 * finestra modale: blocca l'input del Frame sottostante finché l'utente non 
 * sconfigge il nemico, fugge o muore.
 *
 */
public class CombatDialog extends javax.swing.JDialog {
    
    private Zombie zombie;
    private Player player;
    private List<GameObject> inventory;
    
    private boolean combatWon = false;
    private boolean fled = false;
    
    /**
     * Costruisce e inizializza la schermata di combattimento.
     * Oltre a impostare i testi iniziali, si occupa di caricare dinamicamente 
     * l'immagine del nemico, ridimensionandola per adattarla al pannello grafico.
     *
     * @param parent Il frame genitore a cui ancorare questa finestra.
     * @param modal Se {@code true}, blocca le interazioni con il frame padre.
     * @param zombie L'oggetto modello che rappresenta il nemico da affrontare.
     * @param player L'oggetto modello del giocatore (per manipolarne gli HP).
     * @param inventory La lista degli oggetti posseduti per l'uso di armi.
     */
    public CombatDialog(java.awt.Frame parent, boolean modal, Zombie zombie, Player player, List<GameObject> inventory){
        super(parent, modal);
        
        
        initComponents(); 
        
        this.zombie = zombie;
        this.player = player;
        this.inventory = inventory;
        
        
        jLabel1.setText("NEMICO: " + zombie.getName());
        jtaCombatLog.setText(zombie.getDescription() + "\nCosa vuoi fare?");
        
        
        jlPlayerHp.setText("I TUOI HP: " + player.getHp());
        jlZombieHp.setText("HP NEMICO: " + zombie.getLife());
        
       
        try {
            java.net.URL imgURL = getClass().getResource(zombie.getImagePath());
            if (imgURL != null) {
                javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
                java.awt.Image scaled = icon.getImage().getScaledInstance(150, 150, java.awt.Image.SCALE_SMOOTH);
                jlZombieImage.setIcon(new javax.swing.ImageIcon(scaled));
                jlZombieImage.setText(""); 
            }
        } catch (Exception e) {}
        
        
        this.pack(); 
        this.setLocationRelativeTo(parent); 
    }
    
    public boolean isCombatWon() { return combatWon; }
    public boolean hasFled() { return fled; }

    /**
     * Aggiorna l'area di testo (log) del combattimento scorrendo automaticamente 
     * in basso per mostrare l'azione più recente.
     */
    private void logAction(String text) {
        jtaCombatLog.append("\n> " + text);
        jtaCombatLog.setCaretPosition(jtaCombatLog.getDocument().getLength());
    }

    /**
     * Risolve il turno del combattimento.
     * Controlla prima le condizioni di vittoria (morte del nemico). In caso contrario, 
     * elabora il contrattacco dello zombie e aggiorna l'interfaccia.
     */
    private void checkTurn() {
        if (zombie.isDead()) {
            
            jlZombieHp.setText("HP NEMICO: 0");
            
            combatWon = true;
            javax.swing.JOptionPane.showMessageDialog(this, "Hai sconfitto " + zombie.getName() + "!");
            dispose(); 
        } else {
           
            jlZombieHp.setText("HP NEMICO: " + zombie.getLife());
            
            int dmgTaken = zombie.getDamage(); 
            player.setHp(player.getHp() - dmgTaken);
            
            
            int currentHp = Math.max(0, player.getHp());
            jlPlayerHp.setText("I TUOI HP: " + currentHp);
            
            logAction(zombie.getName() + " ti attacca e infligge " + dmgTaken + " danni!");
            
            if (player.getHp() <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "SEI MORTO.", "GAME OVER", javax.swing.JOptionPane.ERROR_MESSAGE);
                dispose();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlZombieHp = new javax.swing.JLabel();
        jlZombieImage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaCombatLog = new javax.swing.JTextArea();
        jlPlayerHp = new javax.swing.JLabel();
        jbFlee = new javax.swing.JButton();
        jbItem = new javax.swing.JButton();
        jbAttack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(20, 20, 20));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 300));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("jLabel1");

        jlZombieHp.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jlZombieHp.setForeground(new java.awt.Color(255, 255, 255));
        jlZombieHp.setText("jLabel2");

        jlZombieImage.setText("jLabel2");
        jlZombieImage.setAlignmentY(0.0F);

        jtaCombatLog.setEditable(false);
        jtaCombatLog.setBackground(new java.awt.Color(31, 25, 18));
        jtaCombatLog.setColumns(20);
        jtaCombatLog.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jtaCombatLog.setForeground(new java.awt.Color(210, 195, 160));
        jtaCombatLog.setRows(5);
        jtaCombatLog.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane1.setViewportView(jtaCombatLog);

        jlPlayerHp.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jlPlayerHp.setForeground(new java.awt.Color(255, 255, 255));
        jlPlayerHp.setText("jLabel2");

        jbFlee.setBackground(new java.awt.Color(85, 70, 50));
        jbFlee.setForeground(new java.awt.Color(210, 195, 160));
        jbFlee.setText("FUGGI");
        jbFlee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbFlee.addActionListener(this::jbFleeActionPerformed);

        jbItem.setBackground(new java.awt.Color(85, 70, 50));
        jbItem.setForeground(new java.awt.Color(210, 195, 160));
        jbItem.setText("USA ZAINO");
        jbItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbItem.addActionListener(this::jbItemActionPerformed);

        jbAttack.setBackground(new java.awt.Color(85, 70, 50));
        jbAttack.setForeground(new java.awt.Color(210, 195, 160));
        jbAttack.setText("ATTACCA");
        jbAttack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbAttack.addActionListener(this::jbAttackActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlZombieImage)
                .addGap(176, 176, 176))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlZombieHp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlPlayerHp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(jbAttack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbFlee)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlZombieHp))
                .addGap(118, 118, 118)
                .addComponent(jlZombieImage)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPlayerHp)
                    .addComponent(jbFlee)
                    .addComponent(jbItem)
                    .addComponent(jbAttack))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Esegue l'attacco base (a mani nude) e invoca il calcolo del turno.
     */
    private void jbAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAttackActionPerformed
        if(zombie.isDead() || player.getHp() <= 0) return;
        int playerDamage = 50; 
        zombie.takeDamage(playerDamage);
        logAction("Hai colpito " + zombie.getName() + " per " + playerDamage + " danni!");
        checkTurn();
    }//GEN-LAST:event_jbAttackActionPerformed

    /**
     * Listener registrato sul bottone "USA ZAINO".
     * Apre in sovraimpressione l'inventario per permettere la selezione di un oggetto.
     * Sfrutta l'operatore {@code instanceof} (RTTI) 
     * per verificare se l'oggetto selezionato è concretamente un'arma ({@link Weapon}) prima 
     * di estrarne il valore di danno e applicarlo al nemico.
     */
    private void jbItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbItemActionPerformed
        if(zombie.isDead() || player.getHp() <= 0) return;
        if (inventory.isEmpty()) {
            logAction("Lo zaino è vuoto!");
            return;
        }
        
        InventoryDialog invDialog = new InventoryDialog((Frame) SwingUtilities.getWindowAncestor(this), inventory);
        invDialog.setVisible(true);

        
        GameObject chosen = invDialog.getSelectedItem();

        if (chosen instanceof Weapon) {
            int itemDmg =((Weapon) chosen).getDamage();
            zombie.takeDamage(itemDmg);
            logAction("Usi [" + chosen.getName() + "] e infliggi " + itemDmg + " danni!");

            
            if (chosen.getName().contains("Ampolla")) {
                inventory.remove(chosen);
            }
            checkTurn();
        }
    }//GEN-LAST:event_jbItemActionPerformed

    /**
     * Listener registrato sul bottone "FUGGI".
     * Chiude la finestra corrente restituendo il controllo alla mappa, ma segnalando 
     * la fuga tramite la flag apposita.
     */
    private void jbFleeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFleeActionPerformed
        fled = true;
        dispose();
    }//GEN-LAST:event_jbFleeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAttack;
    private javax.swing.JButton jbFlee;
    private javax.swing.JButton jbItem;
    private javax.swing.JLabel jlPlayerHp;
    private javax.swing.JLabel jlZombieHp;
    private javax.swing.JLabel jlZombieImage;
    private javax.swing.JTextArea jtaCombatLog;
    // End of variables declaration//GEN-END:variables
}
