   /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package it.map.graphicadventure.progettoesame.view;

/**
 *
 * @author David
 */
public class ConfirmDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConfirmDialog.class.getName());
    
    private boolean confirmed = false; // Registra la scelta del giocatore

    /**
     * Creates new form ConfirmDialog
     */
    public ConfirmDialog(java.awt.Frame parent, boolean modal, String messaggio) {
        super(parent, modal);
        initComponents();
        
        this.getContentPane().setBackground(new java.awt.Color(15, 15, 15));
        jlMessage.setText(messaggio);

        // Centra il testo nella Label 
        jlMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        // Centra il popup rispetto alla finestra di gioco principale
        this.setLocationRelativeTo(parent);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlMessage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jbConfirm = new javax.swing.JButton();
        jbUndo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setPreferredSize(new java.awt.Dimension(400, 180));
        setResizable(false);

        jlMessage.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlMessage.setForeground(new java.awt.Color(255, 255, 255));
        jlMessage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jlMessage, java.awt.BorderLayout.CENTER);

        jPanel1.setOpaque(false);

        jbConfirm.setBackground(new java.awt.Color(0, 0, 0));
        jbConfirm.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jbConfirm.setForeground(new java.awt.Color(0, 204, 0));
        jbConfirm.setText("Conferma");
        jbConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbConfirm.setFocusPainted(false);
        jbConfirm.addActionListener(this::jbConfirmActionPerformed);
        jPanel1.add(jbConfirm);

        jbUndo.setBackground(new java.awt.Color(0, 0, 0));
        jbUndo.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jbUndo.setForeground(new java.awt.Color(204, 0, 0));
        jbUndo.setText("ANNULLA");
        jbUndo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbUndo.setFocusPainted(false);
        jbUndo.addActionListener(this::jbUndoActionPerformed);
        jPanel1.add(jbUndo);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmActionPerformed
        this.confirmed = true;
        
        this.dispose();
    }//GEN-LAST:event_jbConfirmActionPerformed

    private void jbUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUndoActionPerformed
        this.confirmed = false;
        
        this.dispose();
    }//GEN-LAST:event_jbUndoActionPerformed

    
    public boolean isConfirmed() {
        return confirmed;
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbConfirm;
    private javax.swing.JButton jbUndo;
    private javax.swing.JLabel jlMessage;
    // End of variables declaration//GEN-END:variables
}
