/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package it.map.graphicadventure.progettoesame.view;

import java.awt.Color;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import javax.swing.BorderFactory;

/**
 *
 * @author David
 */
public class GameMainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GameMainFrame.class.getName());

    /**
     * Creates new form GameMainFrame
     */
    public GameMainFrame() {
        initComponents();
        
      
        try {
            javax.swing.ImageIcon iconaOriginale = (javax.swing.ImageIcon) jlBackground.getIcon();
            
            if (iconaOriginale != null) {
                java.awt.Image img = iconaOriginale.getImage();
                java.awt.Image imgScalata = img.getScaledInstance(800, 610, java.awt.Image.SCALE_SMOOTH);
                jlBackground.setIcon(new javax.swing.ImageIcon(imgScalata));
            }
        } catch (Exception e) {
            System.out.println("Impossibile ridimensionare lo sfondo: " + e.getMessage());
        }

        
        try {
            java.io.InputStream is = getClass().getResourceAsStream("/fonts/PressStart2P-Regular.ttf");

            // 2. Creiamo l'oggetto Font di Java (formato TrueType)
            Font pixelFontBase = Font.createFont(Font.TRUETYPE_FONT, is);

            // Registriamo il font nell'ambiente grafico di Java
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(pixelFontBase);

            // Creiamo le varianti di dimensione che ci servono
            Font fontTitolo = pixelFontBase.deriveFont(Font.BOLD, 40f);  // Per il titolo
            Font fontBottoni = pixelFontBase.deriveFont(Font.PLAIN, 14f); // Per i pulsanti

            // 5. APPLICHIAMO IL FONT AI COMPONENTI 
            jtfTitle.setFont(fontTitolo);
            jtfTitle.setOpaque(false);
            jtfTitle.setBackground(new Color(0, 0, 0, 0));
            jbNewGame.setFont(fontBottoni);
            jbContinue.setFont(fontBottoni);
            jbQuit.setFont(fontBottoni);
            jbNewGame.setForeground(Color.WHITE); // Fa diventare il testo bianco (o Color.GREEN se lo vuoi verde!)
            jbNewGame.setContentAreaFilled(false); // Rende lo sfondo del bottone trasparente (addio rettangolo grigio!)
            jbNewGame.setBorder(BorderFactory.createLineBorder(Color.WHITE, 2)); // Opzionale: un bel bordo bianco di 2 pixel

        } catch (Exception e) {
            System.out.println("Impossibile caricare la font pixel art: " + e.getMessage());
            // Se fallisce, Swing userà automaticamente la font di default senza crashare
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenu = new javax.swing.JPanel();
        jbNewGame = new javax.swing.JButton();
        jtfTitle = new javax.swing.JTextField();
        jbContinue = new javax.swing.JButton();
        jbQuit = new javax.swing.JButton();
        jlBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Final Exam");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jpMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbNewGame.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbNewGame.setText("NUOVA PARTITA");
        jbNewGame.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jbNewGame.setContentAreaFilled(false);
        jbNewGame.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbNewGame.setFocusPainted(false);
        jbNewGame.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jpMenu.add(jbNewGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 240, 40));

        jtfTitle.setEditable(false);
        jtfTitle.setBackground(new java.awt.Color(0, 0, 0));
        jtfTitle.setFont(new java.awt.Font("Noto Serif Bold", 1, 36)); // NOI18N
        jtfTitle.setForeground(new java.awt.Color(102, 255, 0));
        jtfTitle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfTitle.setText("Final Exam");
        jtfTitle.setBorder(null);
        jtfTitle.setFocusable(false);
        jpMenu.add(jtfTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 590, 70));

        jbContinue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbContinue.setForeground(new java.awt.Color(255, 255, 255));
        jbContinue.setText("CONTINUA");
        jbContinue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jbContinue.setContentAreaFilled(false);
        jbContinue.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbContinue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jpMenu.add(jbContinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 240, 40));

        jbQuit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbQuit.setForeground(new java.awt.Color(204, 0, 0));
        jbQuit.setText("ESCI");
        jbQuit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        jbQuit.setContentAreaFilled(false);
        jbQuit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbQuit.addActionListener(this::jbQuitActionPerformed);
        jpMenu.add(jbQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 220, 50));

        jlBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main_menu_background.png"))); // NOI18N
        jlBackground.setToolTipText("");
        jpMenu.add(jlBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbQuitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GameMainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbContinue;
    private javax.swing.JButton jbNewGame;
    private javax.swing.JButton jbQuit;
    private javax.swing.JLabel jlBackground;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JTextField jtfTitle;
    // End of variables declaration//GEN-END:variables
}
