/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package it.map.graphicadventure.progettoesame.view;

/**
 *
 * @author antoniostilla
 */
public class LeaderboardDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LeaderboardDialog.class.getName());

    /**
     * Creates new form LeaderboardDialog
     */
    public LeaderboardDialog(java.awt.Frame parent, boolean modal, String leaderboardData) {
        super(parent, modal);
        initComponents();
        
        this.setLocationRelativeTo(parent);
        
        // Forza lo sfondo nero del contenitore principale (a volte il Designer lo ignora sui JDialog)
        this.getContentPane().setBackground(new java.awt.Color(20, 20, 20));

        // Inserisce i dati nella Text Area che hai creato
        if (leaderboardData == null || leaderboardData.trim().isEmpty()) {
            jtaScores.setText("\nNessun punteggio disponibile.\nIl server è irraggiungibile o vuoto.");
        } else {
            jtaScores.setText("\n" + leaderboardData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaScores = new javax.swing.JTextArea();
        jbClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(20, 20, 20));

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(210, 195, 160));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TOP 10 - SOPRAVVISSUTI");

        jtaScores.setEditable(false);
        jtaScores.setBackground(new java.awt.Color(10, 10, 10));
        jtaScores.setColumns(20);
        jtaScores.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jtaScores.setForeground(new java.awt.Color(50, 255, 50));
        jtaScores.setRows(5);
        jScrollPane1.setViewportView(jtaScores);

        jbClose.setText("CHIUDI");
        jbClose.setFocusable(false);
        jbClose.addActionListener(this::jbCloseActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 63, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(67, 67, 67))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbClose)
                .addGap(163, 163, 163))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jbClose, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCloseActionPerformed
        dispose();
    }//GEN-LAST:event_jbCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbClose;
    private javax.swing.JTextArea jtaScores;
    // End of variables declaration//GEN-END:variables
}
